version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR (optional, if pushing)
  build:
    commands:
      - echo Building Docker image...
      - docker build -t researchscraper:latest .
artifacts:
  files:
    - '**/*'